on: [push]
#on: [workflow_dispatch]

name: AzARMStorageAccountDeploy

jobs:

    deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Deploy ARM Template
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az deployment group create \
            --name StorageAccountDeployment \
            --resource-group GITHUB-ADO-RG \
            --template-file armtemplates/storageaccount.json \
            --parameters storageAccountType=Standard_GRS
